package sk.epostak.sdk.models;

import java.util.List;

/**
 * Response of {@code GET /api/v1/integrator/licenses/info}.
 * <p>
 * Progressive rates are applied separately to aggregate outbound and inbound
 * usage. Managed sandbox usage is returned separately and excluded from the
 * billed aggregate.
 *
 * @param integrator        integrator metadata (id, name, plan)
 * @param period            current billing period in {@code YYYY-MM} (SK timezone)
 * @param nextResetAt       ISO 8601 - 1st of next month, SK midnight in UTC
 * @param billable          aggregate over firms on the {@code integrator-managed} plan
 * @param sandbox           non-billable managed sandbox usage
 * @param productionEstimate estimate if sandbox firms were billed in production
 * @param nonManaged        linked firms paying their own plan
 * @param exceedsAutoTier   whether the signed schedule requires a custom order above its threshold
 * @param contactThreshold  compatibility threshold from the signed pricing schedule
 * @param pricing           tier table for outbound + inbound API
 * @param firms             paginated per-firm breakdown (sorted by outboundCount desc)
 * @param pagination        pagination envelope
 */
public record IntegratorLicenseInfo(
        Integrator integrator,
        String period,
        String nextResetAt,
        Billable billable,
        Sandbox sandbox,
        Billable productionEstimate,
        NonManaged nonManaged,
        boolean exceedsAutoTier,
        int contactThreshold,
        Pricing pricing,
        List<FirmUsage> firms,
        Pagination pagination
) {

    /**
     * Integrator-level metadata.
     *
     * @param id                   integrator UUID
     * @param name                 integrator display name
     * @param plan                 plan code (e.g. {@code "integrator"})
     * @param monthlyDocumentLimit hard monthly cap, or {@code null} for unlimited
     */
    public record Integrator(
            String id,
            String name,
            String plan,
            Integer monthlyDocumentLimit
    ) {}

    /**
     * Aggregate over firms on the {@code integrator-managed} plan
     * (the integrator pays for these).
     *
     * @param managedFirms     count of firms on the {@code integrator-managed} plan
     * @param maximumActiveFirms maximum active firms observed in the period
     * @param outboundCount    aggregate outbound document count for the period
     * @param inboundApiCount  aggregate inbound API document count for the period
     * @param outboundCharge   tier rates applied to the AGGREGATE outboundCount
     * @param inboundApiCharge tier rates applied to the AGGREGATE inboundApiCount
     * @param apiUsageCharge   sum of outbound and inbound API charges
     * @param whiteLabelBaseCharge contractual white-label base charge
     * @param whiteLabelOverageCharge white-label active-firm overage charge
     * @param totalCharge      total API and contract charge, cents-rounded
     * @param exceedsAutoTier  whether the signed schedule requires a custom order
     * @param currency         always {@code "EUR"}
     */
    public record Billable(
            int managedFirms,
            int maximumActiveFirms,
            int outboundCount,
            int inboundApiCount,
            double outboundCharge,
            double inboundApiCharge,
            double apiUsageCharge,
            double whiteLabelBaseCharge,
            double whiteLabelOverageCharge,
            double totalCharge,
            boolean exceedsAutoTier,
            String currency
    ) {}

    /** Non-billable usage generated by managed sandbox firms. */
    public record Sandbox(
            int firms,
            int outboundCount,
            int inboundApiCount,
            double outboundCharge,
            double inboundApiCharge,
            double totalCharge,
            boolean exceedsAutoTier,
            String currency
    ) {}

    /**
     * Linked firms that pay their own plan (not billed to the integrator).
     *
     * @param firms           number of non-managed firms
     * @param outboundCount   their aggregate outbound count
     * @param inboundApiCount their aggregate inbound API count
     */
    public record NonManaged(
            int firms,
            int outboundCount,
            int inboundApiCount
    ) {}

    /**
     * Pricing table - separate tiers for outbound and inbound API.
     *
     * @param scheduleVersion signed pricing schedule used for the period
     * @param model           always {@code "progressive"}
     * @param currency        always {@code "EUR"}
     * @param thresholdScope  {@code "combined"} or {@code "per_direction"}
     * @param contactThreshold compatibility threshold from the signed schedule
     * @param marginalBandStartsAt first document in the open marginal band
     * @param outboundTiers   outbound tier table
     * @param inboundApiTiers inbound API tier table
     */
    public record Pricing(
            String scheduleVersion,
            String model,
            String currency,
            String thresholdScope,
            int contactThreshold,
            int marginalBandStartsAt,
            List<Tier> outboundTiers,
            List<Tier> inboundApiTiers
    ) {}

    /**
     * One tier in the pricing table. The last entry is an open-ended marginal
     * band with a public rate.
     *
     * @param upTo            inclusive upper bound, or {@code null} on the open tier
     * @param rate            per-document rate in EUR
     * @param label           tier label (e.g. {@code "20 001+"})
     * @param contactRequired whether this tier requires a custom order
     */
    public record Tier(
            Integer upTo,
            double rate,
            String label,
            Boolean contactRequired
    ) {}

    /**
     * Per-firm row in the {@code firms} page.
     *
     * @param firmId          firm UUID
     * @param name            firm display name, or {@code null}
     * @param ico             Slovak ICO, or {@code null}
     * @param managed         {@code true} -&gt; counts in {@link Billable}; {@code false} -&gt; counts in {@link NonManaged}
     * @param sandbox         whether this is an intentionally non-billable sandbox
     * @param billable        whether this firm contributes to the billed aggregate
     * @param outboundCount   firm's outbound count for the period
     * @param inboundApiCount firm's inbound API count for the period
     * @param rebillingEstimate provisional rebilling estimate for this firm
     */
    public record FirmUsage(
            String firmId,
            String name,
            String ico,
            boolean managed,
            boolean sandbox,
            boolean billable,
            int outboundCount,
            int inboundApiCount,
            RebillingEstimate rebillingEstimate
    ) {}

    /** Provisional rebilling estimate for one linked firm. */
    public record RebillingEstimate(
            String currency,
            String pricingMethod,
            Double effectiveOutboundRate,
            Double effectiveInboundApiRate,
            Double outboundAmount,
            Double inboundApiAmount,
            Double totalAmount,
            boolean provisional,
            boolean includedInCurrentBillableAggregate,
            boolean requiresManualReview,
            String note
    ) {}

    /**
     * Pagination envelope for the {@code firms} list.
     *
     * @param limit  page size used for this response
     * @param offset offset used for this response
     * @param total  total firm count for the integrator
     */
    public record Pagination(
            int limit,
            int offset,
            int total
    ) {}
}
