using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace EPostak.Models;

// ---------------------------------------------------------------------------
// Integrator licenses / billing aggregate
// ---------------------------------------------------------------------------

/// <summary>
/// Integrator-level metadata returned inside <see cref="IntegratorLicenseInfo"/>.
/// </summary>
public sealed class IntegratorLicenseInfoIntegrator
{
    /// <summary>Integrator UUID.</summary>
    [JsonPropertyName("id")]
    public string Id { get; set; } = "";

    /// <summary>Integrator display name.</summary>
    [JsonPropertyName("name")]
    public string Name { get; set; } = "";

    /// <summary>Plan code (e.g. <c>integrator</c>).</summary>
    [JsonPropertyName("plan")]
    public string Plan { get; set; } = "";

    /// <summary>Hard monthly document cap, or <c>null</c> for unlimited.</summary>
    [JsonPropertyName("monthlyDocumentLimit")]
    public int? MonthlyDocumentLimit { get; set; }
}

/// <summary>
/// Aggregate over firms on the <c>integrator-managed</c> plan (the integrator
/// is the payer). Tier rates are applied to <see cref="OutboundCount"/> /
/// <see cref="InboundApiCount"/> as a single AGGREGATE — not per-firm.
/// </summary>
public sealed class IntegratorBillableUsage
{
    /// <summary>Number of firms on the <c>integrator-managed</c> plan.</summary>
    [JsonPropertyName("managedFirms")]
    public int ManagedFirms { get; set; }

    /// <summary>Maximum billable active-firm count observed in the period.</summary>
    [JsonPropertyName("maximumActiveFirms")]
    public int MaximumActiveFirms { get; set; }

    /// <summary>Aggregate outbound document count for the period.</summary>
    [JsonPropertyName("outboundCount")]
    public int OutboundCount { get; set; }

    /// <summary>Aggregate inbound API document count for the period.</summary>
    [JsonPropertyName("inboundApiCount")]
    public int InboundApiCount { get; set; }

    /// <summary>Tier rates applied to the aggregate <see cref="OutboundCount"/>.</summary>
    [JsonPropertyName("outboundCharge")]
    public decimal OutboundCharge { get; set; }

    /// <summary>Tier rates applied to the aggregate <see cref="InboundApiCount"/>.</summary>
    [JsonPropertyName("inboundApiCharge")]
    public decimal InboundApiCharge { get; set; }

    /// <summary>Sum of outbound and inbound API usage charges.</summary>
    [JsonPropertyName("apiUsageCharge")]
    public decimal ApiUsageCharge { get; set; }

    /// <summary>Contractual white-label base charge for the period.</summary>
    [JsonPropertyName("whiteLabelBaseCharge")]
    public decimal WhiteLabelBaseCharge { get; set; }

    /// <summary>White-label active-firm overage charge for the period.</summary>
    [JsonPropertyName("whiteLabelOverageCharge")]
    public decimal WhiteLabelOverageCharge { get; set; }

    /// <summary>Total API and contract charge, rounded to cents.</summary>
    [JsonPropertyName("totalCharge")]
    public decimal TotalCharge { get; set; }

    /// <summary>Whether the signed schedule requires a custom order above its threshold.</summary>
    [JsonPropertyName("exceedsAutoTier")]
    public bool ExceedsAutoTier { get; set; }

    /// <summary>Always <c>EUR</c>.</summary>
    [JsonPropertyName("currency")]
    public string Currency { get; set; } = "EUR";
}

/// <summary>Non-billable usage generated by managed sandbox firms.</summary>
public sealed class IntegratorSandboxUsage
{
    [JsonPropertyName("firms")]
    public int Firms { get; set; }

    [JsonPropertyName("outboundCount")]
    public int OutboundCount { get; set; }

    [JsonPropertyName("inboundApiCount")]
    public int InboundApiCount { get; set; }

    [JsonPropertyName("outboundCharge")]
    public decimal OutboundCharge { get; set; }

    [JsonPropertyName("inboundApiCharge")]
    public decimal InboundApiCharge { get; set; }

    [JsonPropertyName("totalCharge")]
    public decimal TotalCharge { get; set; }

    [JsonPropertyName("exceedsAutoTier")]
    public bool ExceedsAutoTier { get; set; }

    [JsonPropertyName("currency")]
    public string Currency { get; set; } = "EUR";
}

/// <summary>
/// Linked firms that pay their own plan (not billed to the integrator).
/// </summary>
public sealed class IntegratorNonManagedUsage
{
    /// <summary>Number of non-managed firms.</summary>
    [JsonPropertyName("firms")]
    public int Firms { get; set; }

    /// <summary>Their aggregate outbound count for the period.</summary>
    [JsonPropertyName("outboundCount")]
    public int OutboundCount { get; set; }

    /// <summary>Their aggregate inbound API count for the period.</summary>
    [JsonPropertyName("inboundApiCount")]
    public int InboundApiCount { get; set; }
}

/// <summary>
/// One row in the pricing tier table. The last entry is an open-ended
/// marginal band with a public rate.
/// </summary>
public sealed class IntegratorPricingTier
{
    /// <summary>Inclusive upper bound of the tier, or <c>null</c> on the open tier.</summary>
    [JsonPropertyName("upTo")]
    public int? UpTo { get; set; }

    /// <summary>Per-document rate in EUR.</summary>
    [JsonPropertyName("rate")]
    public decimal Rate { get; set; }

    /// <summary>Display label on the open tier (e.g. <c>Individuálne</c>); <c>null</c> on the auto-billed tiers.</summary>
    [JsonPropertyName("label")]
    public string? Label { get; set; }

    /// <summary><c>true</c> when this tier requires a sales contract.</summary>
    [JsonPropertyName("contactRequired")]
    public bool? ContactRequired { get; set; }
}

/// <summary>
/// Pricing table — separate tiers for outbound and inbound API.
/// </summary>
public sealed class IntegratorPricing
{
    /// <summary>Signed pricing schedule version used for this billing period.</summary>
    [JsonPropertyName("scheduleVersion")]
    public string ScheduleVersion { get; set; } = "";

    /// <summary>Always <c>progressive</c>.</summary>
    [JsonPropertyName("model")]
    public string Model { get; set; } = "progressive";

    /// <summary>Always <c>EUR</c>.</summary>
    [JsonPropertyName("currency")]
    public string Currency { get; set; } = "EUR";

    /// <summary>Whether the compatibility threshold applies combined or per direction.</summary>
    [JsonPropertyName("thresholdScope")]
    public string ThresholdScope { get; set; } = "";

    /// <summary>Compatibility threshold from the signed pricing snapshot.</summary>
    [JsonPropertyName("contactThreshold")]
    public int ContactThreshold { get; set; }

    /// <summary>First document number in the open-ended marginal band.</summary>
    [JsonPropertyName("marginalBandStartsAt")]
    public int MarginalBandStartsAt { get; set; }

    /// <summary>Outbound tier table.</summary>
    [JsonPropertyName("outboundTiers")]
    public List<IntegratorPricingTier> OutboundTiers { get; set; } = new();

    /// <summary>Inbound API tier table.</summary>
    [JsonPropertyName("inboundApiTiers")]
    public List<IntegratorPricingTier> InboundApiTiers { get; set; } = new();
}

/// <summary>Provisional rebilling estimate for one linked firm.</summary>
public sealed class IntegratorRebillingEstimate
{
    [JsonPropertyName("currency")]
    public string Currency { get; set; } = "EUR";

    [JsonPropertyName("pricingMethod")]
    public string PricingMethod { get; set; } = "";

    [JsonPropertyName("effectiveOutboundRate")]
    public decimal? EffectiveOutboundRate { get; set; }

    [JsonPropertyName("effectiveInboundApiRate")]
    public decimal? EffectiveInboundApiRate { get; set; }

    [JsonPropertyName("outboundAmount")]
    public decimal? OutboundAmount { get; set; }

    [JsonPropertyName("inboundApiAmount")]
    public decimal? InboundApiAmount { get; set; }

    [JsonPropertyName("totalAmount")]
    public decimal? TotalAmount { get; set; }

    [JsonPropertyName("provisional")]
    public bool Provisional { get; set; }

    [JsonPropertyName("includedInCurrentBillableAggregate")]
    public bool IncludedInCurrentBillableAggregate { get; set; }

    [JsonPropertyName("requiresManualReview")]
    public bool RequiresManualReview { get; set; }

    [JsonPropertyName("note")]
    public string Note { get; set; } = "";
}

/// <summary>
/// Per-firm row in the <see cref="IntegratorLicenseInfo.Firms"/> page.
/// </summary>
public sealed class IntegratorFirmUsage
{
    /// <summary>Firm UUID.</summary>
    [JsonPropertyName("firmId")]
    public string FirmId { get; set; } = "";

    /// <summary>Firm display name, or <c>null</c>.</summary>
    [JsonPropertyName("name")]
    public string? Name { get; set; }

    /// <summary>Slovak ICO, or <c>null</c>.</summary>
    [JsonPropertyName("ico")]
    public string? Ico { get; set; }

    /// <summary>
    /// <c>true</c> → counts in <see cref="IntegratorLicenseInfo.Billable"/>;
    /// <c>false</c> → counts in <see cref="IntegratorLicenseInfo.NonManaged"/>.
    /// </summary>
    [JsonPropertyName("managed")]
    public bool Managed { get; set; }

    /// <summary><c>true</c> when this is an intentionally non-billable sandbox.</summary>
    [JsonPropertyName("sandbox")]
    public bool Sandbox { get; set; }

    /// <summary><c>true</c> when this firm contributes to the billed aggregate.</summary>
    [JsonPropertyName("billable")]
    public bool Billable { get; set; }

    /// <summary>Firm's outbound count for the period.</summary>
    [JsonPropertyName("outboundCount")]
    public int OutboundCount { get; set; }

    /// <summary>Firm's inbound API count for the period.</summary>
    [JsonPropertyName("inboundApiCount")]
    public int InboundApiCount { get; set; }

    [JsonPropertyName("rebillingEstimate")]
    public IntegratorRebillingEstimate RebillingEstimate { get; set; } = new();
}

/// <summary>
/// Pagination envelope for the <see cref="IntegratorLicenseInfo.Firms"/> list.
/// </summary>
public sealed class IntegratorLicensePagination
{
    /// <summary>Page size used for this response.</summary>
    [JsonPropertyName("limit")]
    public int Limit { get; set; }

    /// <summary>Offset used for this response.</summary>
    [JsonPropertyName("offset")]
    public int Offset { get; set; }

    /// <summary>Total firm count linked to the integrator.</summary>
    [JsonPropertyName("total")]
    public int Total { get; set; }
}

/// <summary>
/// Response of <c>GET /api/v1/integrator/licenses/info</c>.
/// <para>
/// Progressive rates are applied separately to aggregate outbound and inbound
/// usage. Managed sandbox usage is returned separately and excluded from the
/// billed aggregate.
/// </para>
/// </summary>
public sealed class IntegratorLicenseInfo
{
    /// <summary>Integrator metadata (id, name, plan, optional cap).</summary>
    [JsonPropertyName("integrator")]
    public IntegratorLicenseInfoIntegrator Integrator { get; set; } = new();

    /// <summary>Current billing period in <c>YYYY-MM</c> (SK timezone).</summary>
    [JsonPropertyName("period")]
    public string Period { get; set; } = "";

    /// <summary>ISO 8601 — when counters reset (1st of next month, SK midnight in UTC).</summary>
    [JsonPropertyName("nextResetAt")]
    public string NextResetAt { get; set; } = "";

    /// <summary>Aggregate over firms on the <c>integrator-managed</c> plan (the integrator pays).</summary>
    [JsonPropertyName("billable")]
    public IntegratorBillableUsage Billable { get; set; } = new();

    /// <summary>Managed sandbox usage, priced for visibility but not billed.</summary>
    [JsonPropertyName("sandbox")]
    public IntegratorSandboxUsage Sandbox { get; set; } = new();

    /// <summary>Estimate if managed sandbox firms were included in production billing.</summary>
    [JsonPropertyName("productionEstimate")]
    public IntegratorBillableUsage ProductionEstimate { get; set; } = new();

    /// <summary>Linked firms paying their own plan (not billed to the integrator).</summary>
    [JsonPropertyName("nonManaged")]
    public IntegratorNonManagedUsage NonManaged { get; set; } = new();

    /// <summary>
    /// Historical signed-schedule flag. It stays <c>false</c> for V1.2 because
    /// the 20,001+ marginal band has a public rate.
    /// </summary>
    [JsonPropertyName("exceedsAutoTier")]
    public bool ExceedsAutoTier { get; set; }

    /// <summary>Compatibility threshold; inspect the tier's <c>ContactRequired</c> flag.</summary>
    [JsonPropertyName("contactThreshold")]
    public int ContactThreshold { get; set; }

    /// <summary>Pricing table — separate tiers for outbound and inbound API.</summary>
    [JsonPropertyName("pricing")]
    public IntegratorPricing Pricing { get; set; } = new();

    /// <summary>Per-firm breakdown for the requested page (sorted by outbound count, descending).</summary>
    [JsonPropertyName("firms")]
    public List<IntegratorFirmUsage> Firms { get; set; } = new();

    /// <summary>Pagination envelope for the <see cref="Firms"/> list.</summary>
    [JsonPropertyName("pagination")]
    public IntegratorLicensePagination Pagination { get; set; } = new();
}

/// <summary>One integrator API key row from <c>GET /api/v1/integrator/keys</c>.</summary>
public sealed class IntegratorKey
{
    [JsonPropertyName("id")]
    public string Id { get; set; } = "";

    [JsonPropertyName("keyPrefix")]
    public string KeyPrefix { get; set; } = "";

    [JsonPropertyName("name")]
    public string? Name { get; set; }

    [JsonPropertyName("scopes")]
    public List<string> Scopes { get; set; } = new();

    [JsonPropertyName("ipAllowlist")]
    public List<string> IpAllowlist { get; set; } = new();

    [JsonPropertyName("isActive")]
    public bool IsActive { get; set; }

    [JsonPropertyName("lastUsedAt")]
    public string? LastUsedAt { get; set; }

    [JsonPropertyName("createdAt")]
    public string CreatedAt { get; set; } = "";
}

/// <summary>Response from <c>GET /api/v1/integrator/keys</c>.</summary>
public sealed class IntegratorKeysResponse
{
    [JsonPropertyName("keys")]
    public List<IntegratorKey> Keys { get; set; } = new();
}

/// <summary>Response from <c>DELETE /api/v1/integrator/keys</c>.</summary>
public sealed class DeactivateIntegratorKeyResponse
{
    [JsonPropertyName("success")]
    public bool Success { get; set; }

    [JsonPropertyName("message")]
    public string Message { get; set; } = "";
}
